### ISSUE TITLE
Log entry format

### ISSUE THREAD

**Issue by pshevtsov** [satyrius/gonx#22]
Hello,

I'm trying to process entries with fileds separated by either spaces (one or more) or tabs.

Is it possible to somehow specify such cases in the format string? If not, I could try to implement some FieldsParser (based on https://golang.org/pkg/strings/#Fields). Would you be interested in such pull request?

Thanks

**Comment by satyrius** [comment]
Looks relevant. And this will be much faster then regexp I suppose. But the problem is spaces in a field. How to handle this
```
format := "$remote_addr [$time_local] \"$request\" $status"
line := `89.234.89.123 [08/Nov/2013:13:39:18 +0000] "GET /api/foo/bar HTTP/1.1" 200`
```
Spaces are inside `time` and `request_uri`

**Comment by pshevtsov** [comment]
> And this will be much faster then regexp I suppose.

Yes. I did some benchmarks and results were the following:

1. `strings.Split` (fastest)
1. `strings.Fields`
1. `gonx.Parser.ParseString` (slowest)

**Comment by pshevtsov** [comment]
Some rough implementation of dealing with spaces within fields: http://play.golang.org/p/gJrqdeCr7k

**Comment by satyrius** [comment]
Nice, but you should check format for quotes and brackets to analyse splited parts.

**Comment by pshevtsov** [comment]
Yes, I know. It was just an example of how to split a string by unicode spaces leaving quoted (or wrapped with brackets) fields intact.

**Comment by pshevtsov** [comment]
Check this http://play.golang.org/p/Kv2HcL7wKV It produces better output without quotes and brackets.

**Comment by satyrius** [comment]
Looks awesome! But still, we have to match this with log format to produce an `Entry`.

**Comment by pshevtsov** [comment]
Yup, I'll think about it…

**Comment by pshevtsov** [comment]
Since we have `StringParser` (https://github.com/satyrius/gonx/pull/24) interface it's no longer an issue.
