### ISSUE TITLE
The NewChain duplicate reducers

### ISSUE THREAD

**Issue by sleepdragon** [satyrius/gonx#26]
```go
func NewChain(reducers ...Reducer) *Chain {
	chain := &Chain{
		reducers: reducers,
	}
	for _, r := range reducers {
		if f, ok := interface{}(r).(Filter); ok {
			chain.filters = append(chain.filters, f)
		} else {
			chain.reducers = append(chain.reducers, r)
		}
	}
	return chain
}
```

Is this your original mean?

**Comment by satyrius** [comment]
Sorry, I don;t understand what's the question is? Something wrong with my code?

**Comment by sleepdragon** [comment]
all reducers duplicate in chain.reducers

**Comment by satyrius** [comment]
Sorry for late response, I was busy. And thanks a lot for your attention, it was really a bug! Pull requests with tests are usually improve communication.
