### ISSUE TITLE
go vet errors in benchmark file

### ISSUE THREAD

**Issue by shawnps** [satyrius/gonx#29]
Hi, there are multiple `go vet` errors in `gonx/reader_bench_test.go`:

https://goreportcard.com/report/github.com/satyrius/gonx#go_vet

The `Sprintf` doesn't do anything in these cases because it's not assigned to any variable. You might have meant just `Printf`, or maybe you don't need to print anything at all. Just wanted to let you know.

**Comment by satyrius** [comment]
All done! Thanks for report!
