### ISSUE TITLE
A "Fields" method to get all fields of an Entry

### ISSUE THREAD

**Issue by c625473164** [satyrius/gonx#39]
I wan't to put the results to ElasticSearch.  Is  there any method that can be used to get all fields of an Entry?

**Comment by satyrius** [comment]
There is `Entry.Field` to get a value for the specific field. It's easy to add `Entry.GetFields` to return the whole `map[string]string` structure. Feel free to make a pull request.

**Comment by yaa110** [comment]
please check #40

**Comment by satyrius** [comment]
Thank you for contribution @yaa110
