### ISSUE TITLE
Gzipped files

### ISSUE THREAD

**Issue by bactisme** [satyrius/gonx#41]
Hello, 

(Love your project, great work !!)
I am not able to use the gonx.NewReader on a compress/gzip Reader.
It seems to not be able to read and return 0 lines.

Did you ever tried? Do you have any idea of the problem?
**Nevermind, it work flawlessly, you can delete this issue **

Thanks

**Comment by satyrius** [comment]
Glad it works for you! Feel free to open a Pull Request if you need something specific.
