### ISSUE TITLE
A new release?

### ISSUE THREAD

**Issue by xgfone** [satyrius/gonx#46]

**Comment by satyrius** [comment]
Hey! What do you expect from it?

**Comment by xgfone** [comment]
Last released version is on `Dec 19, 2015`. During this period, there are some new commits and the new API, that's, `Entry.Fields() Fields`. Does it need to release a new version now?

**PS:** I need to use the method `Entry.Fields() Fields` and don't like the pseudo-version. Thanks.

**Comment by satyrius** [comment]
It makes sense. I’m gonna make it.

**Comment by satyrius** [comment]
I collected changes that accumulated over the years and published them https://github.com/satyrius/gonx/releases/tag/v1.4.0
