### ISSUE TITLE
gonx.Reader Returns EOF without returning anything

### ISSUE THREAD

**Issue by aman00323** [satyrius/gonx#47]
- I was trying to parse some logs with this beautiful package, but I get EOF.
- Even though I have debug inside package `MapReduce` it is reading lines.
- But `Read()`  isn't returning it.

Any Help on that

**Comment by satyrius** [comment]
Hello @aman00323 ! In order to help you, I need you to share the code. So I can reproduce the bug.

**Comment by aman00323** [comment]
@satyrius I have figured out the issue, that was due to the incorrect format of log. I am wondering that if we can have a feature that detects log format while reading lines.
