### ISSUE TITLE
Regarding donating project 

### ISSUE THREAD

**Issue by pratikbin** [satyrius/gonx#48]
Hello @satyrius, thanks for this amazing project. Hope you're doing well

We(as a team) have created a GitHub org called [daftcreations](https://github.com/daftcreations/) for OSS projects and for educations content on [YouTube](https://www.youtube.com/c/DaftCreation/videos). All members were colleagues once. The thought of creating org was from using day to day life tools, most of the themes were the open-source or some part of them. I, Myself, have contributed to many OSS projects and most of the members of org members as well. We got a team of awesome Designers, UI, UX, Frontend, Backend, ChainOps(blockchain DevOps like myself) and DevOps people. And that inspires us to contribute our expertise to the open-source world, and make it better. This is the way.

We jointly created our first project called [gcps](http://github.com/daftcreation/gcps) which is gcloud profile switcher, which was initiated by [@naman2706](https://github.com/naman2706) and other devs, we're just on the edge of releasing it.

So, We wanted you to donate(transfer) this awesome project to our org. Our amazing golang dev [@aman00323](https://github.com/aman00323) and [@naman2706](https://github.com/naman2706) will look into it and try to give it a new life with the latest golang knowledge.

Fin

**Comment by aman00323** [comment]
@satyrius ^^
